import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.*;
import com.tngtech.archunit.lang.*;
import com.tngtech.archunit.lang.conditions.ArchConditions;
import com.tngtech.archunit.library.Architectures;
import com.tngtech.archunit.library.GeneralCodingRules;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.*;
import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;

import java.util.LinkedHashMap;
import java.util.Map;

/** Generated by enforcer. Edits are overwritten on the next run. */
public final class GeneratedRules {

    public static Map<String, ArchRule> rules() {
        Map<String, ArchRule> rules = new LinkedHashMap<>();
        rules.put("no-impl-interfaces-archunit",
                noClasses().that().areInterfaces()
                .should().haveSimpleNameEndingWith("Impl"));
        return rules;
    }

    private GeneratedRules() {
    }
}
