"""ArchUnit: compile a rule expression and evaluate it against compiled classes."""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from core.result import ERROR, PASS, SKIP, VIOLATION, Result

MODULE = Path(__file__).resolve().parent
JAR = MODULE / "target" / "enforcer-archunit.jar"
GENERATED = MODULE / "src" / "main" / "java" / "GeneratedRules.java"
GENERATED_CLASS = MODULE / "target" / "classes" / "GeneratedRules.class"

#: The imports every generated expression is compiled against. ONE definition, read by three callers.
IMPORTS = """\
import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.*;
import com.tngtech.archunit.lang.*;
import com.tngtech.archunit.lang.conditions.ArchConditions;
import com.tngtech.archunit.library.Architectures;
import com.tngtech.archunit.library.GeneralCodingRules;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.*;
import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;\
"""

#: Overwritten on every run. This is the compilation unit the jar actually executes.
_TEMPLATE = IMPORTS + """

import java.util.LinkedHashMap;
import java.util.Map;

/** Generated by enforcer. Edits are overwritten on the next run. */
public final class GeneratedRules {

    public static Map<String, ArchRule> rules() {
        Map<String, ArchRule> rules = new LinkedHashMap<>();
%(entries)s
        return rules;
    }

    private GeneratedRules() {
    }
}
"""


def _identifier(rule_id: str) -> str:
    """A rule id as a legal Java class name -- a kebab-case dash and a leading digit are not."""
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", rule_id).strip("_") or "rule"
    return "Rule_" + cleaned


def render_file(rule: dict) -> str:
    """One generated rule as a COMPLETE, standalone-compilable Java file -- not the execution path."""
    body = "\n".join(line.rstrip() for line in rule["rule"]).strip().rstrip(";")
    indented = ("\n" + " " * 12).join(body.splitlines())
    name = _identifier(rule["id"])
    return (f"// Generated by enforcer -- a COMPLETE compilation unit.\n"
            f"// id:     {rule['id']}\n"
            f"// source: {rule['source']}\n"
            f"//\n"
            f"// Compile it on its own to type-check the rule:\n"
            f"//     javac -cp enforcer/archunit/target/enforcer-archunit.jar <this file>\n"
            f"//\n"
            f"// NOT the execution path: `execute` reads the expression from rules.json.\n"
            f"\n{IMPORTS}\n\n"
            f"final class {name} {{\n\n"
            f"    static final ArchRule RULE =\n"
            f"            {indented};\n\n"
            f"    private {name}() {{\n"
            f"    }}\n"
            f"}}\n")


def find_classes(repo: Path) -> list[Path]:
    """Compiled output directories in a repository, Maven and Gradle."""
    found = [path for pattern in ("target/classes", "build/classes/java/main")
             for path in repo.rglob(pattern) if path.is_dir() and any(path.rglob("*.class"))]
    return sorted(set(found))


def compile_tree(tree: Path, into: Path) -> Path | None:
    """Compile every .java under `tree` into `into` with no classpath, or None if it does not compile."""
    into.mkdir(parents=True, exist_ok=True)
    files = [str(p) for p in Path(tree).rglob("*.java")]
    if not files:
        return None
    done = subprocess.run(["javac", "--release", "21", "-d", str(into), *files],
                          capture_output=True)
    return into if done.returncode == 0 else None


# ------------------------------------------------------------------ the pipeline path


def write_rules(rules: list[dict]) -> None:
    """Render a run's rules into the Maven module's GeneratedRules.java, ready for `mvn package`."""
    entries = "\n".join(
        f'        rules.put("{rule["id"]}",\n                '
        + "\n                ".join(line.rstrip() for line in rule["rule"]).strip()
        + ");"
        for rule in rules) or "        // no rules generated"
    GENERATED.write_text(_TEMPLATE % {"entries": entries}, encoding="utf-8")


def run(rules: list[dict], repo: Path, classes: list[Path] | None = None,
        tools: dict | None = None) -> Result:
    """Compile a run's rules into the jar, then evaluate them against the project's bytecode."""
    if not rules:
        return Result(SKIP, "no archunit rules generated")
    tools = tools or {}
    maven, java = tools.get("mvn"), tools.get("java")
    if not maven or not java:
        return Result(SKIP, "mvn or java is not on PATH -- the jar cannot be rebuilt")

    classes = classes or find_classes(repo)
    if not classes:
        return Result(SKIP, f"no compiled classes under {repo} -- build it first, or pass "
                            "--classes")

    write_rules(rules)
    # Remove our one generated class so Maven cannot skip the compile and shade an IDE's output.
    GENERATED_CLASS.unlink(missing_ok=True)
    build = subprocess.run([maven, "-q", "package"], cwd=MODULE, capture_output=True,
                           text=True, timeout=900)
    if build.returncode != 0:
        # Almost always an expression that does not compile; the rendered file is left to read.
        return Result(ERROR, f"jar build failed -- see {GENERATED}\n"
                             + (build.stdout or build.stderr).strip()[:3000])

    done = subprocess.run([java, "-jar", str(JAR), *[str(c) for c in classes]],
                          capture_output=True, text=True, timeout=900)
    output = (done.stdout or "").strip()
    errors = (done.stderr or "").strip()
    findings = output.count("VIOLATION  ")
    # Only the three codes Runner.java defines are trusted; anything else is ERROR, never PASS.
    if done.returncode == 0:
        return Result(PASS, output)
    if done.returncode == 1:
        # Runner.java prints a `VIOLATION` line per failure, so exit 1 with none means the JVM died.
        if findings == 0:
            return Result(ERROR, ("archunit exited 1 without reporting a violation -- the JVM "
                                  "died before the report was written\n"
                                  + "\n".join(part for part in (output, errors) if part))[:2000])
        return Result(VIOLATION, output, findings)
    if done.returncode == 2:
        return Result(ERROR, "\n".join(part for part in (output, errors) if part)[:2000])
    return Result(ERROR, f"archunit exited with an unexpected status {done.returncode}\n"
                         + "\n".join(part for part in (output, errors) if part)[:2000])


# -------------------------------------------------------------------- the single-rule path

_HOST = """\
import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.*;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.lang.*;
import com.tngtech.archunit.lang.conditions.ArchConditions;
import com.tngtech.archunit.library.Architectures;
import com.tngtech.archunit.library.GeneralCodingRules;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.*;
import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;
import java.nio.file.*;
%(imports)s
public class H {
  static final ArchRule R = %(rule)s;
  public static void main(String[] a) throws Exception {
    JavaClasses cs = new ClassFileImporter().importPath(Paths.get(a[0]));
    if (cs.size() == 0) { System.out.println("ZERO"); return; }
    try { R.check(cs); System.out.println("PASS"); }
    catch (AssertionError e) {
      System.out.println(e.getMessage().contains("failed to check any classes")
          ? "EMPTY-SELECTOR" : "VIOLATION");
    }
  }
}
"""


def _class_literal_imports(expression: str, tree: Path) -> str:
    """Imports for any `T.class` literal the expression names, with the package read from the file."""
    lines = []
    for symbol in sorted(set(re.findall(r"\b([A-Z]\w*)\.class\b", expression))):
        for source in sorted(Path(tree).rglob(f"{symbol}.java")):
            package = re.search(r"^\s*package\s+([\w.]+)\s*;",
                                source.read_text(encoding="utf-8", errors="replace"), re.M)
            if package:
                lines.append(f"import {package.group(1)}.{symbol};")
                break
    return "\n".join(lines)


def evaluate(expression: str, classes: Path | None, tree: Path, scratch: Path) -> Result:
    """Evaluate ONE expression against one class directory, without touching the shared module."""
    if classes is None:
        return Result(ERROR, "the tree under analysis does not compile")
    scratch.mkdir(parents=True, exist_ok=True)
    host = scratch / "H.java"
    host.write_text(_HOST % {"imports": _class_literal_imports(expression, tree),
                             "rule": expression.strip().rstrip(";")}, encoding="utf-8")

    # The tree's own compiled classes must be on the classpath, since framework types may be stubs.
    compiled = subprocess.run(["javac", "-cp", f"{JAR}:{classes}", "-d", str(scratch),
                               str(host)], capture_output=True, text=True)
    if compiled.returncode != 0:
        return Result(ERROR, "the rule does not compile: "
                             + (compiled.stderr or "").strip().splitlines()[0][:200]
                      if compiled.stderr else "the rule does not compile")

    done = subprocess.run(["java", "-cp", f"{JAR}:{scratch}:{classes}", "H", str(classes)],
                          capture_output=True, text=True, timeout=300)
    word = next((w for w in done.stdout.split()
                 if w in ("PASS", "VIOLATION", "ZERO", "EMPTY-SELECTOR")), None)
    if word == "PASS":
        return Result(PASS, "")
    if word == "VIOLATION":
        return Result(VIOLATION, "", 1)
    if word == "ZERO":
        return Result(ERROR, "no classes imported -- nothing was examined")
    if word == "EMPTY-SELECTOR":
        return Result(ERROR, "the selector matched no classes -- nothing was examined")
    return Result(ERROR, _diagnosis(done.stderr, done.stdout))


#: Lines the JVM emits on every run regardless of outcome, long enough to crowd out a real diagnosis.
_JVM_NOISE = ("SLF4J(W):", "SLF4J:", "WARNING: A terminally deprecated method",
              "WARNING: sun.misc.Unsafe", "WARNING: Please consider reporting",
              "WARNING: System::load", "WARNING: A restricted method")


def _diagnosis(stderr: str, stdout: str) -> str:
    """The first line that actually says something, not the first line printed."""
    for stream in (stderr or "", stdout or ""):
        lines = [l.strip() for l in stream.splitlines() if l.strip()
                 and not any(l.lstrip().startswith(n) for n in _JVM_NOISE)]
        if lines:
            return " | ".join(lines[:3])[:400]
    return "the rule did not run, and neither stream said why"
